# Generated by Django 2.0.3 on 2018-04-21 16:45

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('genre', models.CharField(choices=[('C', 'Comedy'), ('D', 'Documentary'), ('H', 'Horror'), ('RC', 'Romantic Comedy'), ('SF', 'Sci-Fi'), ('D', 'Drama'), ('Cl', 'Classic'), ('CC', 'Cult Classic')], default='D', max_length=2, null=True)),
                ('rotten_tomatoes_score', models.PositiveSmallIntegerField(null=True)),
                ('imdb_score', models.PositiveSmallIntegerField(default=0, null=True)),
                ('imdb_url', models.URLField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.SmallIntegerField()),
                ('comment', models.TextField(blank=True, default='', max_length=1000)),
                ('reviewed_on', models.DateField(auto_now_add=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.Movie')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('followed_users', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None)),
                ('friends_list', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None)),
                ('movies_wanting_to_see', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), null=True, size=None)),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='reviewer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.User'),
        ),
    ]
