# Generated by Django 2.0.3 on 2018-04-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('C', 'Comedy'), ('D', 'Documentary'), ('H', 'Horror'), ('RC', 'Romantic Comedy'), ('SF', 'Sci-Fi'), ('D', 'Drama'), ('Cl', 'Classic'), ('CC', 'Cult Classic')], default='D', max_length=2),
        ),
    ]
