# Generated by Django 2.0.3 on 2018-04-08 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20180406_1832'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='comments',
            field=models.TextField(blank=True, default=''),
        ),
    ]
