# Generated by Django 2.0.3 on 2018-04-22 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20180421_1557'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.AddField(
            model_name='movie',
            name='length',
            field=models.CharField(default='90 min', max_length=20),
        ),
        migrations.AddField(
            model_name='movie',
            name='rating',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
