# Generated by Django 2.0.3 on 2018-04-29 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_auto_20180429_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewer',
            name='following',
            field=models.ManyToManyField(null=True, to='movies.Reviewer'),
        ),
    ]
