# Generated by Django 2.0.3 on 2018-04-29 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20180429_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewer',
            name='following',
            field=models.ManyToManyField(blank=True, to='movies.Reviewer'),
        ),
    ]
