# Generated by Django 2.0.3 on 2018-04-29 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20180429_0909'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.CharField(default='1984', max_length=4),
            preserve_default=False,
        ),
    ]
